# Primary site settings
title: "Hello. I'm Jason Zhu."
description: "I'm a software developer from Winnipeg fascinated in machine learning models."
project_hook: "Find Out More"
email: 'jzcompsci@gmail.com'
baseurl: "" 
url: "https://jz-fsdev.github.io/creative-theme-jekyll" 
linkedin_username: 'jason-zhu-dev'
github_username: 'jz-fsdev'
resume_url: "https://drive.google.com/file/d/1xvVEJ49xLR6rN5V1Bjb8lFt8caCwBFK8/view?usp=drive_link"

# Head/Nav settings
site_title: "Jason Zhu"

# Contact settings
contact_heading: "Let's Get In Touch!"
contact_paragraph: "I am always open to collaborating on new projects to push my boundaries and grow as a software developer.  Send me an email or reach out to me on LinkedIn and I will respond at my earliest convenience."

# Project settings
p1_category:
p1_name:

p2_category:
p2_name:

p3_category: "Plant Molecular Biology Research"
p3_name: "Polyketide Synthases"
p3_url: 

# About settings
about_heading: "Everyone's journey before pursuing computer science is different."
about_description: "I come from a background in general sciences, which opened my eyes to the complexity of the world and taught me the importance of accuracy and novel discovery, not only in experiments but also in everything we do in life. My time as an operations manager at a local family restaurant allowed me to witness firsthand how quality and strict adherence to guidelines translate into happy and satisfied customers. These lessons and experiences guide my journey in the pursuit of developing high-quality and innovative software that brings smiles to customers' faces."

# Build settings
markdown: kramdown

footer_text: '© 2023 Jason Zhu'
google_analytics: ""